//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Embedded {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Embedded() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMS.Resources.Embedded", typeof(Embedded).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bug.
        /// </summary>
        public static string FeedbackBug {
            get {
                return ResourceManager.GetString("FeedbackBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string FeedbackClose {
            get {
                return ResourceManager.GetString("FeedbackClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Try contacting us by mail..
        /// </summary>
        public static string FeedbackContactByMail {
            get {
                return ResourceManager.GetString("FeedbackContactByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A comment, a question, a difficulty? Thanks to provide as much detail as possible..
        /// </summary>
        public static string FeedbackDetailReport {
            get {
                return ResourceManager.GetString("FeedbackDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait....
        /// </summary>
        public static string FeedbackPleaseWait {
            get {
                return ResourceManager.GetString("FeedbackPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        public static string FeedbackQuestion {
            get {
                return ResourceManager.GetString("FeedbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your submission was not sent..
        /// </summary>
        public static string FeedbackReportFailded {
            get {
                return ResourceManager.GetString("FeedbackReportFailded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your submission has been received, we will review it shortly..
        /// </summary>
        public static string FeedbackReportSubmitted {
            get {
                return ResourceManager.GetString("FeedbackReportSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not saved!.
        /// </summary>
        public static string FeedbackSaveFailed {
            get {
                return ResourceManager.GetString("FeedbackSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit Report.
        /// </summary>
        public static string FeedbackSubmitReport {
            get {
                return ResourceManager.GetString("FeedbackSubmitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Take Screenshot.
        /// </summary>
        public static string FeedbackTakeScreenshot {
            get {
                return ResourceManager.GetString("FeedbackTakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tell us more....
        /// </summary>
        public static string FeedbackTellUsMore {
            get {
                return ResourceManager.GetString("FeedbackTellUsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you!.
        /// </summary>
        public static string FeedbackThankYou {
            get {
                return ResourceManager.GetString("FeedbackThankYou", resourceCulture);
            }
        }
    }
}
