//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMS.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to select one.
        /// </summary>
        public static string ApplicationsClickToSelect {
            get {
                return ResourceManager.GetString("ApplicationsClickToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applications come from the scan of users ping and known applications inside them..
        /// </summary>
        public static string ApplicationsExplanation {
            get {
                return ResourceManager.GetString("ApplicationsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1st ping:.
        /// </summary>
        public static string ApplicationsFirstPing {
            get {
                return ResourceManager.GetString("ApplicationsFirstPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last ping:.
        /// </summary>
        public static string ApplicationsLastPing {
            get {
                return ResourceManager.GetString("ApplicationsLastPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applications Management.
        /// </summary>
        public static string ApplicationsManagement {
            get {
                return ResourceManager.GetString("ApplicationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No applications, no users pings &gt; check if your server is reachable from apps.
        /// </summary>
        public static string ApplicationsNoPing {
            get {
                return ResourceManager.GetString("ApplicationsNoPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active and registered Apps.
        /// </summary>
        public static string ApplicationsRegistered {
            get {
                return ResourceManager.GetString("ApplicationsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active and registered Applications.
        /// </summary>
        public static string ApplicationsRegisteredTitle {
            get {
                return ResourceManager.GetString("ApplicationsRegisteredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string ApplicationsSelectAll {
            get {
                return ResourceManager.GetString("ApplicationsSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all applications.
        /// </summary>
        public static string ApplicationsSelectAllTitle {
            get {
                return ResourceManager.GetString("ApplicationsSelectAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application code.
        /// </summary>
        public static string DashboardApplicationCode {
            get {
                return ResourceManager.GetString("DashboardApplicationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application.
        /// </summary>
        public static string DashboardApps {
            get {
                return ResourceManager.GetString("DashboardApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exception.
        /// </summary>
        public static string DashboardException {
            get {
                return ResourceManager.GetString("DashboardException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No feedback.
        /// </summary>
        public static string DashboardFeedbackNo {
            get {
                return ResourceManager.GetString("DashboardFeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show feedbacks list.
        /// </summary>
        public static string DashboardFeedbackTitle {
            get {
                return ResourceManager.GetString("DashboardFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs by Type.
        /// </summary>
        public static string DashboardLogsByType {
            get {
                return ResourceManager.GetString("DashboardLogsByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à on last 30 minutes.
        /// </summary>
        public static string DashboardLogsOnLast30min {
            get {
                return ResourceManager.GetString("DashboardLogsOnLast30min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs received.
        /// </summary>
        public static string DashboardLogsReceived {
            get {
                return ResourceManager.GetString("DashboardLogsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show logs list.
        /// </summary>
        public static string DashboardLogsTitle {
            get {
                return ResourceManager.GetString("DashboardLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monitoring.
        /// </summary>
        public static string DashboardMonitoring {
            get {
                return ResourceManager.GetString("DashboardMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinted pages history.
        /// </summary>
        public static string DashboardMonitoringHintedPagesHistory {
            get {
                return ResourceManager.GetString("DashboardMonitoringHintedPagesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinted pages history.
        /// </summary>
        public static string DashboardMonitoringHintedPagesHistoryTitle {
            get {
                return ResourceManager.GetString("DashboardMonitoringHintedPagesHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Instant pages loaded (10s).
        /// </summary>
        public static string DashboardMonitoringInstantPagesLoaded {
            get {
                return ResourceManager.GetString("DashboardMonitoringInstantPagesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à on last 5 minutes.
        /// </summary>
        public static string DashboardMonitoringOnLast5min {
            get {
                return ResourceManager.GetString("DashboardMonitoringOnLast5min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Online Users.
        /// </summary>
        public static string DashboardMonitoringOnlineUsers {
            get {
                return ResourceManager.GetString("DashboardMonitoringOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Online users history.
        /// </summary>
        public static string DashboardMonitoringOnlineUsersHistory {
            get {
                return ResourceManager.GetString("DashboardMonitoringOnlineUsersHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Online users history.
        /// </summary>
        public static string DashboardMonitoringOnlineUsersHistoryTitle {
            get {
                return ResourceManager.GetString("DashboardMonitoringOnlineUsersHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show statistics list.
        /// </summary>
        public static string DashboardMonitoringTitle {
            get {
                return ResourceManager.GetString("DashboardMonitoringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Received Logs history.
        /// </summary>
        public static string DashboardReceivedLogsHistory {
            get {
                return ResourceManager.GetString("DashboardReceivedLogsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Received Logs history.
        /// </summary>
        public static string DashboardReceivedLogsHistoryTitle {
            get {
                return ResourceManager.GetString("DashboardReceivedLogsHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.
        /// </summary>
        public static string DashboardTime {
            get {
                return ResourceManager.GetString("DashboardTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unanswered.
        /// </summary>
        public static string DashboardUnansweredFeedback {
            get {
                return ResourceManager.GetString("DashboardUnansweredFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to home.
        /// </summary>
        public static string ErrorBackHome {
            get {
                return ResourceManager.GetString("ErrorBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 404 Not found.
        /// </summary>
        public static string ErrorHttp404 {
            get {
                return ResourceManager.GetString("ErrorHttp404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exception is Null.
        /// </summary>
        public static string ErrorNullException {
            get {
                return ResourceManager.GetString("ErrorNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while processing your request.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Page.
        /// </summary>
        public static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page doesn&apos;t exist, sorry.
        /// </summary>
        public static string ErrorPageNotFound {
            get {
                return ResourceManager.GetString("ErrorPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, the error has been reported to the Application administrator.
        /// </summary>
        public static string ErrorReportedToAdmin {
            get {
                return ResourceManager.GetString("ErrorReportedToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string FeedbackAll {
            get {
                return ResourceManager.GetString("FeedbackAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application:.
        /// </summary>
        public static string FeedbackApplication {
            get {
                return ResourceManager.GetString("FeedbackApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bug.
        /// </summary>
        public static string FeedbackBug {
            get {
                return ResourceManager.GetString("FeedbackBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string FeedbackClose {
            get {
                return ResourceManager.GetString("FeedbackClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedback Detail #.
        /// </summary>
        public static string FeedbackDetailId {
            get {
                return ResourceManager.GetString("FeedbackDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedback #.
        /// </summary>
        public static string FeedbackId {
            get {
                return ResourceManager.GetString("FeedbackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedbacks List.
        /// </summary>
        public static string FeedbackList {
            get {
                return ResourceManager.GetString("FeedbackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string FeedbackNew {
            get {
                return ResourceManager.GetString("FeedbackNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string FeedbackOpen {
            get {
                return ResourceManager.GetString("FeedbackOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page:.
        /// </summary>
        public static string FeedbackPage {
            get {
                return ResourceManager.GetString("FeedbackPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        public static string FeedbackQuestion {
            get {
                return ResourceManager.GetString("FeedbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedbacks.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string FeedbackStatus {
            get {
                return ResourceManager.GetString("FeedbackStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User:.
        /// </summary>
        public static string FeedbackUser {
            get {
                return ResourceManager.GetString("FeedbackUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User wrote:.
        /// </summary>
        public static string FeedbackUserWrote {
            get {
                return ResourceManager.GetString("FeedbackUserWrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string HomeAbout {
            get {
                return ResourceManager.GetString("HomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Applications.
        /// </summary>
        public static string HomeActiveApplications {
            get {
                return ResourceManager.GetString("HomeActiveApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinted Pages.
        /// </summary>
        public static string HomeHintedPages {
            get {
                return ResourceManager.GetString("HomeHintedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Online Users.
        /// </summary>
        public static string HomeOnlineUsers {
            get {
                return ResourceManager.GetString("HomeOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs &amp; Monitoring Services.
        /// </summary>
        public static string HomeShitsukeSummary {
            get {
                return ResourceManager.GetString("HomeShitsukeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and more.
        /// </summary>
        public static string HomeShitsukeSummaryMore {
            get {
                return ResourceManager.GetString("HomeShitsukeSummaryMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à by period to .
        /// </summary>
        public static string LmsByPeriodTo {
            get {
                return ResourceManager.GetString("LmsByPeriodTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count.
        /// </summary>
        public static string LmsCount {
            get {
                return ResourceManager.GetString("LmsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation Date.
        /// </summary>
        public static string LmsCreationDate {
            get {
                return ResourceManager.GetString("LmsCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string LmsId {
            get {
                return ResourceManager.GetString("LmsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        public static string LmsLevel {
            get {
                return ResourceManager.GetString("LmsLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string LmsMessage {
            get {
                return ResourceManager.GetString("LmsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data.
        /// </summary>
        public static string LmsNoData {
            get {
                return ResourceManager.GetString("LmsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string LmsType {
            get {
                return ResourceManager.GetString("LmsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Url.
        /// </summary>
        public static string LmsUrl {
            get {
                return ResourceManager.GetString("LmsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locked..
        /// </summary>
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This account has been locked, please try again..
        /// </summary>
        public static string LockoutAccountLocked {
            get {
                return ResourceManager.GetString("LockoutAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application:.
        /// </summary>
        public static string LogApplication {
            get {
                return ResourceManager.GetString("LogApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string LogCode {
            get {
                return ResourceManager.GetString("LogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Context.
        /// </summary>
        public static string LogContext {
            get {
                return ResourceManager.GetString("LogContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation Date:.
        /// </summary>
        public static string LogCreationDate {
            get {
                return ResourceManager.GetString("LogCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail.
        /// </summary>
        public static string LogDetail {
            get {
                return ResourceManager.GetString("LogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host.
        /// </summary>
        public static string LogHost {
            get {
                return ResourceManager.GetString("LogHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Http Method.
        /// </summary>
        public static string LogHttpMethod {
            get {
                return ResourceManager.GetString("LogHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID:.
        /// </summary>
        public static string LogId {
            get {
                return ResourceManager.GetString("LogId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to change your password.
        /// </summary>
        public static string LoginChangePassword {
            get {
                return ResourceManager.GetString("LoginChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IP Address.
        /// </summary>
        public static string LogIpAddress {
            get {
                return ResourceManager.GetString("LogIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Machine.
        /// </summary>
        public static string LogMachine {
            get {
                return ResourceManager.GetString("LogMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs analysis.
        /// </summary>
        public static string LogsAnalysis {
            get {
                return ResourceManager.GetString("LogsAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log detail.
        /// </summary>
        public static string LogsDetail {
            get {
                return ResourceManager.GetString("LogsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First Time.
        /// </summary>
        public static string LogsFirstTime {
            get {
                return ResourceManager.GetString("LogsFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hash code of log.
        /// </summary>
        public static string LogsHashCode {
            get {
                return ResourceManager.GetString("LogsHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last date.
        /// </summary>
        public static string LogsLastDate {
            get {
                return ResourceManager.GetString("LogsLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Time.
        /// </summary>
        public static string LogsLastTime {
            get {
                return ResourceManager.GetString("LogsLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List.
        /// </summary>
        public static string LogsList {
            get {
                return ResourceManager.GetString("LogsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à logs.
        /// </summary>
        public static string LogsMin {
            get {
                return ResourceManager.GetString("LogsMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data for this log - this is an unique log.
        /// </summary>
        public static string LogsNoData {
            get {
                return ResourceManager.GetString("LogsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurence.
        /// </summary>
        public static string LogsOccurence {
            get {
                return ResourceManager.GetString("LogsOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurences.
        /// </summary>
        public static string LogsOccurences {
            get {
                return ResourceManager.GetString("LogsOccurences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string LogSource {
            get {
                return ResourceManager.GetString("LogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL.
        /// </summary>
        public static string LogSql {
            get {
                return ResourceManager.GetString("LogSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status code.
        /// </summary>
        public static string LogStatusCode {
            get {
                return ResourceManager.GetString("LogStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web.
        /// </summary>
        public static string LogWeb {
            get {
                return ResourceManager.GetString("LogWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Date.
        /// </summary>
        public static string PeriodChooseDate {
            get {
                return ResourceManager.GetString("PeriodChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Period.
        /// </summary>
        public static string PeriodChoosePeriod {
            get {
                return ResourceManager.GetString("PeriodChoosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Day.
        /// </summary>
        public static string PeriodLastDay {
            get {
                return ResourceManager.GetString("PeriodLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Month.
        /// </summary>
        public static string PeriodLastMonth {
            get {
                return ResourceManager.GetString("PeriodLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Week.
        /// </summary>
        public static string PeriodLastWeek {
            get {
                return ResourceManager.GetString("PeriodLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applications Management.
        /// </summary>
        public static string SidebarApplicationsManagement {
            get {
                return ResourceManager.GetString("SidebarApplicationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard.
        /// </summary>
        public static string SidebarDashboard {
            get {
                return ResourceManager.GetString("SidebarDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedbacks List.
        /// </summary>
        public static string SidebarFeedbacksList {
            get {
                return ResourceManager.GetString("SidebarFeedbacksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs List.
        /// </summary>
        public static string SidebarLogsList {
            get {
                return ResourceManager.GetString("SidebarLogsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My own exceptions.
        /// </summary>
        public static string SidebarMyOwnExceptions {
            get {
                return ResourceManager.GetString("SidebarMyOwnExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinted Statistics.
        /// </summary>
        public static string SidedarHintedStatistics {
            get {
                return ResourceManager.GetString("SidedarHintedStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string StatBrowserName {
            get {
                return ResourceManager.GetString("StatBrowserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinted Statistics.
        /// </summary>
        public static string StatHinted {
            get {
                return ResourceManager.GetString("StatHinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average.
        /// </summary>
        public static string StatHintedAverage {
            get {
                return ResourceManager.GetString("StatHintedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max.
        /// </summary>
        public static string StatHintedMax {
            get {
                return ResourceManager.GetString("StatHintedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pages on last .
        /// </summary>
        public static string StatHintedPagesOnLast {
            get {
                return ResourceManager.GetString("StatHintedPagesOnLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinted .
        /// </summary>
        public static string StatHintedShort {
            get {
                return ResourceManager.GetString("StatHintedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top page.
        /// </summary>
        public static string StatHintedTopPages {
            get {
                return ResourceManager.GetString("StatHintedTopPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string StatHintedTotal {
            get {
                return ResourceManager.GetString("StatHintedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users on last .
        /// </summary>
        public static string StatHintedUsersOnLast {
            get {
                return ResourceManager.GetString("StatHintedUsersOnLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à % of total.
        /// </summary>
        public static string StatPercentage {
            get {
                return ResourceManager.GetString("StatPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Screen size.
        /// </summary>
        public static string StatScreenSize {
            get {
                return ResourceManager.GetString("StatScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technologies analysis on period.
        /// </summary>
        public static string StatTechnoAnalysis {
            get {
                return ResourceManager.GetString("StatTechnoAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browser type.
        /// </summary>
        public static string StatTechnoBrowserType {
            get {
                return ResourceManager.GetString("StatTechnoBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Screen.
        /// </summary>
        public static string StatTechnoScreen {
            get {
                return ResourceManager.GetString("StatTechnoScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OS.
        /// </summary>
        public static string StatTecnoOs {
            get {
                return ResourceManager.GetString("StatTecnoOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hits.
        /// </summary>
        public static string StatTopPagesHits {
            get {
                return ResourceManager.GetString("StatTopPagesHits", resourceCulture);
            }
        }
    }
}
