//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesJS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesJS() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMS.Resources.ResourcesJS", typeof(ResourcesJS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t set it.
        /// </summary>
        public static string ApplicationErrorTxt {
            get {
                return ResourceManager.GetString("ApplicationErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set to {0}.
        /// </summary>
        public static string ApplicationSuccessTxt {
            get {
                return ResourceManager.GetString("ApplicationSuccessTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current application.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string BootgridAll {
            get {
                return ResourceManager.GetString("BootgridAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Showing {{ctx.start}} to {{ctx.end}} of {{ctx.total}} entries.
        /// </summary>
        public static string BootgridInfos {
            get {
                return ResourceManager.GetString("BootgridInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string BootgridLoading {
            get {
                return ResourceManager.GetString("BootgridLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No result found!.
        /// </summary>
        public static string BootgridNoResult {
            get {
                return ResourceManager.GetString("BootgridNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        public static string BootgridRefresh {
            get {
                return ResourceManager.GetString("BootgridRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string BootgridSearch {
            get {
                return ResourceManager.GetString("BootgridSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All applications.
        /// </summary>
        public static string DashboardAllApplications {
            get {
                return ResourceManager.GetString("DashboardAllApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Answered.
        /// </summary>
        public static string FeedbackAnswered {
            get {
                return ResourceManager.GetString("FeedbackAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bug.
        /// </summary>
        public static string FeedbackBug {
            get {
                return ResourceManager.GetString("FeedbackBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t find the right feedback.
        /// </summary>
        public static string FeedbackCannotFind {
            get {
                return ResourceManager.GetString("FeedbackCannotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Closed.
        /// </summary>
        public static string FeedbackClosed {
            get {
                return ResourceManager.GetString("FeedbackClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string FeedbackNew {
            get {
                return ResourceManager.GetString("FeedbackNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opened.
        /// </summary>
        public static string FeedbackOpened {
            get {
                return ResourceManager.GetString("FeedbackOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        public static string FeedbackQuestion {
            get {
                return ResourceManager.GetString("FeedbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t save this status. Re-try later..
        /// </summary>
        public static string FeedbackStatusSavedError {
            get {
                return ResourceManager.GetString("FeedbackStatusSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New status saved.
        /// </summary>
        public static string FeedbackStatusSavedSuccess {
            get {
                return ResourceManager.GetString("FeedbackStatusSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save a new status.
        /// </summary>
        public static string FeedbackStatusSavedTxt {
            get {
                return ResourceManager.GetString("FeedbackStatusSavedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t find the right log.
        /// </summary>
        public static string LogCannotFind {
            get {
                return ResourceManager.GetString("LogCannotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find by hashcode.
        /// </summary>
        public static string LogFindByHashcode {
            get {
                return ResourceManager.GetString("LogFindByHashcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search and load.
        /// </summary>
        public static string LogSearchAndLoad {
            get {
                return ResourceManager.GetString("LogSearchAndLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 24 hours.
        /// </summary>
        public static string Period24Hours {
            get {
                return ResourceManager.GetString("Period24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30 days.
        /// </summary>
        public static string Period30Days {
            get {
                return ResourceManager.GetString("Period30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7 days.
        /// </summary>
        public static string Period7Days {
            get {
                return ResourceManager.GetString("Period7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à d.
        /// </summary>
        public static string PeriodDays1stLetterMin {
            get {
                return ResourceManager.GetString("PeriodDays1stLetterMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à h.
        /// </summary>
        public static string PeriodHours1stLetterMin {
            get {
                return ResourceManager.GetString("PeriodHours1stLetterMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
    }
}
